// Code generated by mockery v1.0.0. DO NOT EDIT.

package service

import context "context"
import echo "github.com/labstack/echo/v4"
import mock "github.com/stretchr/testify/mock"
import model "github.com/AndiVS/myapp3.0/internal/model"

// Users is an autogenerated mock type for the Users type
type MockUsers struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: c, username
func (_m *MockUsers) DeleteUser(c context.Context, username string) error {
	ret := _m.Called(c, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: c
func (_m *MockUsers) GetUser(c context.Context, username string) (*model.User, error) {
	ret := _m.Called(c, username)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(c, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUser provides a mock function with given fields: c
func (_m *MockUsers) GetAllUser(c context.Context) ([]*model.User, error) {
	ret := _m.Called(c)

	var r0 []*model.User
	if rf, ok := ret.Get(0).(func(context.Context) []*model.User); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: c, username, isAdmin
func (_m *MockUsers) UpdateUser(c context.Context, username string, isAdmin bool) error {
	ret := _m.Called(c, username, isAdmin)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(c, username, isAdmin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddU provides a mock function with given fields: c, rec
func (_m *MockUsers) SignUp(c context.Context, rec *model.User, hashSalt string) error {
	ret := _m.Called(c, rec)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(c, rec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SignIn provides a mock function with given fields: c, user
func (_m *MockUsers) SignIn(c echo.Context, user *model.User, hashSalt string, access *JWTManager, refresh *JWTManager) error {
	ret := _m.Called(c, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, *model.User) error); ok {
		r0 = rf(c, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TokenRefresherMiddleware provides a mock function with given fields: next
func (_m *MockUsers) TokenRefresherMiddleware(next echo.HandlerFunc) echo.HandlerFunc {
	ret := _m.Called(next)

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func(echo.HandlerFunc) echo.HandlerFunc); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}
